// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zebroapqzyblmcyrgvic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplYnJvYXBxenlibG1jeXJndmljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODM4OTMsImV4cCI6MjA2Mjk1OTg5M30.MN5xaRtx6wofqHEv9DFtHTGLLa3StTrmc4YI1ajMjcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);